### PR TITLE
Add Wikipedia provider

### PR DESCRIPTION
**Pull request by arunisaac**
I have added a provider for Wikipedia. As promised! :-)

### CODE REVIEW

**Comment by SirCmpwn** [comment]
LGTM, thanks!

**Comment by arunisaac** [comment]
I see a lot of potential for code reuse in providers.

For example, why not have the parent Provider class have basic prepare
and execute methods that a child provider (say, the Wikipedia provider)
could inherit? The behaviour of the basic prepare and execute methods in
the parent class could be modified by member variables such as
login_url, password_change_url, username_field, password_field,
etc. Many simple providers would be able to just inherit Provider and
tweak a few of these member variables instead of having to redefine
their own prepare and execute methods. More complicated providers could
have their own prepare and execute methods. This could greatly simplify
the addition of new providers.

What do you think? Shall I send a pull request implementing this?

**Comment by SirCmpwn** [comment]
We already have pretty solid support code and writing a provider is already pretty easy. I'm not sure simplifying it any further is necessary or desirable. Your wikipedia provider is already dead simple.

**Comment by arunisaac** [comment]
Maybe, you're right and I'm overthinking this.

But, maintaining these providers can become tedious. For example, we
want to introduce custom exceptions as mentioned in #31. We want all
providers to be standardized so that they raise the same exceptions. The
only way to do it now is to modify all providers. That is so many
redundant edits. But, if we had inheritance, we might ideally have to
edit only one file at one place. That's nice and DRY.

Also, inheritance with the child classes only tweaking some member
variables is good parameterization. It makes the providers more
declarative instead of just being amorphous blocks of procedural code.

**Comment by SirCmpwn** [comment]
I'm not convinced.

**Pull request merged**
