### PR TITLE
providers: add reddit

### PR DESCRIPTION
**Pull request by adtac**
Partially closes https://github.com/SirCmpwn/pass-rotate/issues/9

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Can this be done without relying on old.reddit.com? I have a feeling it's not going to stick around for long.

**Comment by adtac** [comment]
I have no intentions to try this out on new.reddit.com. In fact I have an extension to redirect me from reddit.com to old.reddit.com all the time in case I get linked to that abomination by mistake. Completely irrational from me, but the new design drives me nuts. Sorry I can't help in that aspect. Happy to let anybody else that wants to experiment (note: it won't be trivial, as I don't think `s/old.reddit.com/reddit.com` will work).

FWIW, https://old.reddit.com/r/help/comments/8mi7v2/for_how_long_will_old_reddit_be_supported/ reasons that the old version will exist for a long time. Obviously the reddit from years ago is not the reddit now, so we have no idea if the current management will continue to be kind enough to let older versions of their software stay.

**Comment by adtac** [comment]
>Reddit has said they've got no plans to sunset the old design

from that thread; the comment didn't provide an official source, however

**Comment by SirCmpwn** [comment]
>FWIW, https://old.reddit.com/r/help/comments/8mi7v2/for_how_long_will_old_reddit_be_supported/ reasons that the old version will exist for a long time. Obviously the reddit from years ago is not the reddit now, so we have no idea if the current management will continue to be kind enough to let older versions of their software stay.

This is a straight-up lie

I'm not comfortable merging a provider that could easily break within months.

**Comment by adtac** [comment]
Fair enough. I'll close the PR. If someone wants to build on this work, feel free to do so :)

And to whoever implements the more robust code, if it's not too much trouble, if you can mention me when it's merged, that'd be great!

For now I'll be using my fork just for reddit. Sigh, I have to remember to occassionally pull from upstream.

>I'm not comfortable merging a provider that could easily break within months.

Just my two cents: frontend interfaces change all the time, and keeping up with them is near impossible. A lot of the code in this repo has hard-coded form IDs and whatnot, which will break eventually. Of course, there's no other alternative, which is pretty sad because these providers could easily provide a simple API for something like this.

**Comment by SirCmpwn** [comment]
>Just my two cents: frontend interfaces change all the time, and keeping up with them is near impossible. A lot of the code in this repo has hard-coded form IDs and whatnot, which will break eventually. Of course, there's no other alternative, which is pretty sad because these providers could easily provide a simple API for something like this.

Aye, that's a reality we have to live with. But we could stand to not implement something when we know a breaking change is around the corner, especially when we can already access the new version for developing a more long-term solution with.

**Comment by alphapapa** [comment]
> I'm not comfortable merging a provider that could easily break within months.

Unfortunately, that's probably true.  I'm sure that as soon as any kind of security vulnerability is found in old.reddit.com's code, or whenever it becomes the least bit inconvenient for them to keep it available, they will drop it.

**Pull request closed without merging**
