### PR TITLE
pixiv: Use more accurate login error messages

### PR DESCRIPTION
**Pull request by tsudoko**
Looks like pixiv sometimes requires solving a captcha to log in. No requests are performed before a captcha box appears (and it only appears after clicking "login"), so detecting it doesn't seem like a simple task.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Can you detect the captcha and modify the prompt function to support captcha input?

**Comment by tsudoko** [comment]
> Can you detect the captcha

I tried doing that at first. Looks like I've missed something, since it can be actually detected easily. I'll add that.

> and modify the prompt function to support captcha input?

It uses Google's reCAPTCHA, so I'm not sure how a text-only prompt could work with it (other than perhaps "log in manually and paste your cookies here").

**Comment by GrayHatter** [comment]
Could you download the audio file, and switch to solving the audio captcha?

**Comment by SirCmpwn** [comment]
You don't necessarily need to make something that's solvable at the command line, fwiw. Just provide all of the information you have to prompt and let the user of the library (be that the pass-rotate CLI or something else) sort it out. Then for the CLI, if you can't present the user with a means of solving it, detect the captcha case and throw an error.

**Comment by SirCmpwn** [comment]
Closing as this seems to be abandoned.

**Pull request closed without merging**
